import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

function Header() {
  return (
    <header>
      <div className="badge">
        <Image src="/img/logo.svg" alt="Dente Fácil" width={118} height={35} />
      </div>
      <div className="menubar">
        <Image src="/img/hamburger.svg" alt="Menu" width={45} height={45} />
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer>
      <div className="info">Dente Fácil</div>
      <div className="version">versão MVP</div>
    </footer>
  );
}
